/* ═══════════════════════════════════════════════════════════════════════════
 *     ╔═══════════════════════════════════════════════════════════════╗
 *     ║                    OBFUSCATED C CODE                         ║
 *     ║                  Generated by Obfuscator                     ║
 *     ╚═══════════════════════════════════════════════════════════════╝
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdio.h>

/* ✧･ﾟ: *✧･ﾟ:* Obfuscated Beauty *:･ﾟ✧*:･ﾟ✧ */
int __aesthetic_func_001(int __aesthetic_var_002) {
    if (__aesthetic_var_002 <= 1) {
        return 1;
    }
    return __aesthetic_var_002 * __aesthetic_func_001(__aesthetic_var_002 - 1);
}

/* ◆◇◆◇◆ Encrypted Logic ◆◇◆◇◆ */
int main() {
    int __aesthetic_var_004 = 5;
    printf("Factorial of %d is %d\n", __aesthetic_var_004, __aesthetic_func_001(__aesthetic_var_004));
    return 0;
}