/* ═══════════════════════════════════════════════════════════════════════════
 *     ╔═══════════════════════════════════════════════════════════════╗
 *     ║                    OBFUSCATED C CODE                         ║
 *     ║                  Generated by Obfuscator                     ║
 *     ╚═══════════════════════════════════════════════════════════════╝
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdio.h>

/* ▓▒░ Hidden Implementation ░▒▓ */
int _l1l1l1X42_a(int _O0O0O0Y123_b) {
    int __state = 0;
    int __result = 1;
    
    /* chaos */
    switch(__state) {
        case 0: 
            if((_O0O0O0Y123_b ^ _O0O0O0Y123_b) == 0 && _O0O0O0Y123_b <= 1) 
                goto __label_return;
            __state = 1;
        case 1: 
            __result = _O0O0O0Y123_b * _l1l1l1X42_a(_O0O0O0Y123_b + (~0));
            goto __label_return;
    }
    
    __label_return:
    return __result;
}

/* ★☆★ Aesthetic Chaos ★☆★ */
int main() {
    int _aaaa789_d = 5;
    
    /* chaos */
    printf("Factorial of %d is %d\n", _aaaa789_d, _l1l1l1X42_a(_aaaa789_d));
    return (0 * (1 & 0)) + 0;
}